#!/usr/bin/env python3
"""
prove_paper.py -- EXACT (symbolic) verification of the algebra in
"Discreteness as the Late-Time Limit of a Smooth Flow"  (README.md and APPENDIX.md).

verify_paper.py samples random points in 50-digit arithmetic.  This script does something
different: every identity is proved for ALL real x and ALL k = e^{-2 pi t} > 0 by computer algebra.

Method
------
Write c = cos 2 pi x, s = sin 2 pi x, k = e^{-2 pi t}.  Every quantity in the note is a rational
function of (c, s, k) (pi appears only as a constant P that cancels; the checks are done with P a
free positive symbol, which is stronger than P = pi).  A rational identity f = 0 holds at every real
point of the circle s^2 + c^2 = 1 iff the numerator of f lies in the ideal generated by s^2+c^2-1;
for a single irreducible generator this is a polynomial division with remainder 0.  That is an exact
decision procedure -- no sampling, no floating point, and no problem at the half-integers (c = -1),
where tan is undefined.  Derivatives are taken by the chain rule on (c, s, k):
    d/dx c = -2 P s,  d/dx s = 2 P c,  d/dt k = -2 P k,   d/dy atan(w) = w'/(1+w^2).

Logical structure (what is proved here, and what is a standard theorem)
-----------------------------------------------------------------------
Labels are sections of README.md / APPENDIX.md ("Res" = Result of README.md Section 3).
 ALGEBRA (this script, exact)
   A.1   D, E > 0 ;  2k^2 <= E <= 2 for k <= 1                      (Appendix A.1; the bound is used in C.4)
   A.2   D^2 + ((1-k) sin)^2 = 2E ;  1 + w^2 = 2E/D^2                (Appendix A.2)
   A.3   tangent-coordinate algebra (T = tan pi(x-n)); the cell form solves the SAME initial-value
         problem as the closed form                                    (Appendix A.3, branch-free argument)
   B     dR/dx = 2k/E on ALL of R, boundaries included ;  dR/dt = -sin(2 pi R) ;
         sin(2 pi R) = 2k sin(2 pi x)/E ;  R_0 = id                    (Results 1, 2; Appendix B)
   Res1  1 + cos(2 pi R) = 2(1+c)/E ;  tan(pi R) = k tan(pi x)         (Result 1, linearizing form)
   C.1   slopes 2k/E = k, 1/k at c = +1, -1                            (Appendix C.1)
   C.2   d/dt V(R) = -sin^2(2 pi R)                                    (Appendix C.2)
   C.3   monotonicity in t from the cell form                          (Appendix C.3; also Result 4 limit)
   D     arctan identity and the unresolved fraction                   (Appendix D)
   E     Moebius form, multiplier, velocity addition, hyperbolic distance, Poisson density (Appendix E)
   4,F   resolution-time algebra, expansions, the table of Appendix F  (Section 4, Appendix F)
 STANDARD THEOREMS (not mechanised here; each is one line given the algebra above)
   T1  Picard-Lindelof uniqueness for y' = -sin(2 pi y) (globally Lipschitz, constant 2 pi)
        => B + R_0 = id means the closed form IS the flow => group law, inverse (Result 3)
        => A.3 gives cell form = closed form
   T2  continuous + strictly increasing + commutes with shifts => bijection of R (Result 2)
   T3  mean value theorem (C.4);  continuity of arctan at 0 (Result 4)

Usage:  python prove_paper.py        (needs sympy and mpmath; exit status 0 iff everything passes)
"""
import sys

import sympy as sp
from mpmath import mp, mpf, tan as mtan, atan as matan, log as mlog, pi as mpi, nstr

# ----------------------------------------------------------------------------------------------
P = sp.symbols("P", positive=True)          # stands for pi
k = sp.symbols("k", positive=True)          # contraction factor e^{-2 pi t}
c, s = sp.symbols("c s", real=True)         # cos 2 pi x, sin 2 pi x
T = sp.symbols("T", real=True)              # tan pi (x - n)
tau = sp.symbols("tau", real=True)          # rational parametrisation of the circle

CIRCLE = s**2 + c**2 - 1
PARAM = {c: (1 - tau**2) / (1 + tau**2), s: 2 * tau / (1 + tau**2)}

D = (1 + c) + k * (1 - c)
E = (1 + c) + k**2 * (1 - c)
w = (1 - k) * s / D                        # argument of the arctangent in the closed form
# R_t(x) = x - atan(w)/P   (P = pi)


def dx(f):
    return sp.diff(f, c) * (-2 * P * s) + sp.diff(f, s) * (2 * P * c)


def dt(f):
    return sp.diff(f, k) * (-2 * P * k)


def zero_on_circle(expr):
    """Exact: True iff expr == 0 at every real point with s^2+c^2=1 (and every k>0, P>0)."""
    num, _ = sp.fraction(sp.together(expr))
    num = sp.expand(num)
    if num == 0:
        return True
    _, rem = sp.reduced(num, [CIRCLE], s, c, k, P)
    return sp.expand(rem) == 0


def zero_param(expr):
    """Independent second decision procedure: substitute the rational parametrisation of the
    circle (covers every point except c=-1, which is handled by continuity / direct substitution)."""
    return sp.cancel(sp.together(expr.subs(PARAM, simultaneous=True))) == 0


ROWS = []


def check(label, ok):
    ROWS.append((label, bool(ok)))


def identity(label, expr):
    a, b = zero_on_circle(expr), zero_param(expr)
    check(label + ("" if a == b else "  [DECISION PROCEDURES DISAGREE]"), a and b)


# derived trigonometric quantities of the transformed angle 2 pi R = 2 pi x - 2 atan(w)
cos2atan = (1 - w**2) / (1 + w**2)
sin2atan = 2 * w / (1 + w**2)
sinR = s * cos2atan - c * sin2atan          # sin(2 pi R)
cosR = c * cos2atan + s * sin2atan          # cos(2 pi R)

# ==============================================================================================
# 0. The two standard trig facts used to expand sin/cos of (2 pi x - 2 atan w)
# ==============================================================================================
ww, th = sp.symbols("ww theta", real=True)
check("0  sin(2 atan w) = 2w/(1+w^2)", sp.simplify(sp.sin(2 * sp.atan(ww)).expand(trig=True) - 2 * ww / (1 + ww**2)) == 0)
check("0  cos(2 atan w) = (1-w^2)/(1+w^2)", sp.simplify(sp.cos(2 * sp.atan(ww)).expand(trig=True) - (1 - ww**2) / (1 + ww**2)) == 0)
check("0  tan(y) = sin(2y)/(1+cos(2y))  (half-angle)",
      sp.simplify((sp.sin(2 * th) / (1 + sp.cos(2 * th))) - sp.tan(th)) == 0)
check("0  e^{-2i atan w} = (1-iw)/(1+iw)",
      sp.simplify(sp.expand((1 - sp.I * ww) ** 2 / (1 + ww**2)) - (cos2atan.subs(w, ww) - sp.I * sin2atan.subs(w, ww))) == 0)

# ==============================================================================================
# A.1  positivity and bounds
# ==============================================================================================
check("A.1 D, E are affine in c", sp.diff(D, c, 2) == 0 and sp.diff(E, c, 2) == 0)
check("A.1 endpoints: D(c=-1)=2k, D(c=1)=2, E(c=-1)=2k^2, E(c=1)=2",
      sp.simplify(D.subs(c, -1) - 2 * k) == 0 and sp.simplify(D.subs(c, 1) - 2) == 0
      and sp.simplify(E.subs(c, -1) - 2 * k**2) == 0 and sp.simplify(E.subs(c, 1) - 2) == 0)
#  affine on [-1,1]  =>  min at an endpoint  =>  D >= 2 min(1,k) > 0 and E >= 2 min(1,k^2) > 0   (k > 0 arbitrary)
check("A.1 E - 2k^2 = (1-k^2)(1+c)   and   2 - E = (1-k^2)(1-c)   (=> 2k^2 <= E <= 2 for k <= 1; used in C.4)",
      sp.expand(E - 2 * k**2 - (1 - k**2) * (1 + c)) == 0 and sp.expand(2 - E - (1 - k**2) * (1 - c)) == 0)

# ==============================================================================================
# A.2  algebraic core (Appendix A.2)
# ==============================================================================================
identity("A.2 D^2 + ((1-k) s)^2 = 2E", D**2 + ((1 - k) * s) ** 2 - 2 * E)
identity("A.2 1 + w^2 = 2E/D^2", 1 + w**2 - 2 * E / D**2)

# ==============================================================================================
# 2.1 / A.3  tangent-coordinate algebra (n = 0 WLOG: c, s are 1-periodic in x)
# ==============================================================================================
cT, sT = (1 - T**2) / (1 + T**2), 2 * T / (1 + T**2)
DT, ET = D.subs({c: cT, s: sT}), E.subs({c: cT, s: sT})
q = (1 - k) * T / (1 + k * T**2)
check("A.3 sin 2pi x = 2T/(1+T^2), 1+cos = 2/(1+T^2), 1-cos = 2T^2/(1+T^2) (double angle, T=tan; also 2.1)",
      sp.simplify(sp.sin(2 * th) - 2 * sp.tan(th) / (1 + sp.tan(th) ** 2)) == 0
      and sp.simplify(1 + sp.cos(2 * th) - 2 / (1 + sp.tan(th) ** 2)) == 0
      and sp.simplify(1 - sp.cos(2 * th) - 2 * sp.tan(th) ** 2 / (1 + sp.tan(th) ** 2)) == 0)
check("A.3 q := (1-k) sin/D = (1-k)T/(1+kT^2)", sp.cancel((1 - k) * sT / DT - q) == 0)
check("A.3 (T-q)/(1+qT) = kT", sp.cancel((T - q) / (1 + q * T) - k * T) == 0)
check("A.3 D = 2(1+kT^2)/(1+T^2),  E = 2(1+k^2T^2)/(1+T^2)",
      sp.cancel(DT - 2 * (1 + k * T**2) / (1 + T**2)) == 0 and sp.cancel(ET - 2 * (1 + k**2 * T**2) / (1 + T**2)) == 0)

# ==============================================================================================
# B  Results 1, 2:  derivatives of the CLOSED form on the whole line
# ==============================================================================================
dRdx = 1 - dx(w) / (P * (1 + w**2))
dRdt = -dt(w) / (P * (1 + w**2))
identity("B  dR/dx = 2k/E   (Result 2; closed form, every x incl. half-integers)", dRdx - 2 * k / E)
identity("B  sin(2 pi R) = 2k sin(2 pi x)/E", sinR - 2 * k * s / E)
identity("B  dR/dt = -sin(2 pi R)   (Result 1)", dRdt + sinR)
check("B  R_0 = id  (Result 1; k=1 gives w=0)", sp.simplify(w.subs(k, 1)) == 0)
identity("B  sin^2 + cos^2 = 1 for the transformed angle (consistency)", sinR**2 + cosR**2 - 1)

# C.2 : chain rule  d/dt V(R) = V'(R) dR/dt  with V' = sin(2 pi y)
y = sp.symbols("y", real=True)
check("C.2 V(y) = -cos(2 P y)/(2 P)  =>  V'(y) = sin(2 P y)", sp.simplify(sp.diff(-sp.cos(2 * P * y) / (2 * P), y) - sp.sin(2 * P * y)) == 0)
identity("C.2 d/dt V(R) = sin(2 pi R) dR/dt = -sin^2(2 pi R)", sinR * dRdt + sinR**2)

# cross-check of B with sympy.diff on the genuine trigonometric expression (no hand-made chain rule)
xx, tt = sp.symbols("xx tt", real=True)
Kt = sp.exp(-2 * sp.pi * tt)
Dd = (1 + sp.cos(2 * sp.pi * xx)) + Kt * (1 - sp.cos(2 * sp.pi * xx))
Rg = xx - sp.atan((1 - Kt) * sp.sin(2 * sp.pi * xx) / Dd) / sp.pi
back = {sp.sin(2 * sp.pi * xx): s, sp.cos(2 * sp.pi * xx): c, sp.exp(-2 * sp.pi * tt): k}
gx = sp.diff(Rg, xx).subs(back).subs(sp.pi, P)
gt = sp.diff(Rg, tt).subs(back).subs(sp.pi, P)
check("B' sympy.diff of the trig closed form: no x,t left after substitution", not (gx.free_symbols & {xx, tt}) and not (gt.free_symbols & {xx, tt}))
identity("B' sympy.diff:  dR/dx = 2k/E", gx - 2 * k / E)
identity("B' sympy.diff:  dR/dt = -2 k s ... = -sin(2 pi R)", gt + 2 * k * s / E)

# ==============================================================================================
# C.1  slopes at the fixed points
# ==============================================================================================
check("C.1 slope at integers 2k/E|_{c=1} = k ;  at half-integers 2k/E|_{c=-1} = 1/k",
      sp.simplify(2 * k / E.subs(c, 1) - k) == 0 and sp.simplify(2 * k / E.subs(c, -1) - 1 / k) == 0)
check("C.1 both are fixed: w = 0 where s = 0", sp.simplify(w.subs(s, 0)) == 0)

# ==============================================================================================
# Result 1 (linearizing form)
# ==============================================================================================
identity("Res1 1 + cos(2 pi R) = 2(1+c)/E   (so cos(pi R) = 0 iff cos(pi x) = 0)", 1 + cosR - 2 * (1 + c) / E)
identity("Res1 tan(pi R) = k tan(pi x):  sin(2 pi R)(1+c) = k s (1+cos 2 pi R)", sinR * (1 + c) - k * s * (1 + cosR))

# ==============================================================================================
# A.3  The cell form solves the same IVP as the closed form  (the branch-free argument of Appendix A.3)
# ==============================================================================================
Cell = sp.atan(k * T) / P                    # R - n, as a function of (T, k)
dCdt = sp.diff(Cell, k) * (-2 * P * k)
sinC = 2 * k * T / (1 + k**2 * T**2)         # sin(2 pi (R-n)) = sin(2 atan(kT))
check("A.3 sin(2 atan(kT)) = 2kT/(1+k^2T^2)", sp.simplify(sp.sin(2 * sp.atan(k * T)).expand(trig=True) - sinC) == 0)
check("A.3 d/dt [n + atan(kT)/pi] = -sin(2 pi R)  (cell form solves the ODE)", sp.simplify(dCdt + sinC) == 0)
check("A.3 d/dx cell form = k(1+T^2)/(1+k^2T^2) = 2k/E  (dT/dx = pi(1+T^2))",
      sp.cancel(sp.diff(Cell, T) * P * (1 + T**2) - 2 * k / ET) == 0)
check("A.3 cell form at t=0 is x:  d/du[atan(tan u) - u] = 0 on (-pi/2, pi/2) and = 0 at u = 0",
      sp.simplify(sp.diff(sp.atan(sp.tan(th)) - th, th)) == 0 and sp.atan(sp.tan(0)) - 0 == 0)
# => closed form and cell form solve  y' = -sin(2 pi y), y(0) = x ;  by Lipschitz uniqueness (T1) they coincide.

# ==============================================================================================
# Result 4 and C.3 from the cell form  R - n = atan(kT)/pi  (T = tan pi(x-n), finite on the open cell)
# ==============================================================================================
uu = sp.symbols("uu", real=True)
check("Res4 |atan u| <= |u|:  d/du (u - atan u) = u^2/(1+u^2) >= 0   =>  |R_t - n| <= k|T|/pi -> 0 as t -> inf",
      sp.simplify(sp.diff(uu - sp.atan(uu), uu) - uu**2 / (1 + uu**2)) == 0)
check("C.3 T * d/dk atan(kT) = T^2/(1+k^2T^2) >= 0  =>  |R_t - n| = |atan(kT)|/pi is nondecreasing in k, i.e. NONINCREASING in t -- for ALL real s <= t",
      sp.simplify(T * sp.diff(sp.atan(k * T), k) - T**2 / (1 + k**2 * T**2)) == 0)

# ==============================================================================================
# E  Appendix E (geometric reading)
# ==============================================================================================
z = sp.symbols("z")
r = (1 - k) / (1 + k)                         # = tanh(pi t)
check("E  r = tanh(pi t)  <=>  (1-k)/(1+k) with k = e^{-2 pi t}",
      sp.simplify((sp.tanh(sp.pi * sp.Symbol("t", real=True))).rewrite(sp.exp)
                  - (1 - sp.exp(-2 * sp.pi * sp.Symbol("t", real=True))) / (1 + sp.exp(-2 * sp.pi * sp.Symbol("t", real=True)))) == 0)
cz, sz = (z + 1 / z) / 2, (z - 1 / z) / (2 * sp.I)
wz = ((1 - k) * sz / ((1 + cz) + k * (1 - cz)))
lhs = z * (1 - sp.I * wz) / (1 + sp.I * wz)     # e^{2 pi i R} = z e^{-2i atan w}
check("E  e^{2 pi i R} = (z + r)/(1 + r z)   (exact, z on the unit circle parametrised freely)", sp.cancel(sp.together(lhs - (z + r) / (1 + r * z))) == 0)
mob = (z + r) / (1 + r * z)
check("E  multiplier at +1 = (1-r)/(1+r) = k ;  at -1 = (1+r)/(1-r) = 1/k",
      sp.simplify(sp.diff(mob, z).subs(z, 1) - k) == 0 and sp.simplify(sp.diff(mob, z).subs(z, -1) - 1 / k) == 0)
check("E  Moebius map fixes +1 and -1", sp.simplify(mob.subs(z, 1) - 1) == 0 and sp.simplify(mob.subs(z, -1) + 1) == 0)
ks, kt = sp.symbols("k_s k_t", positive=True)
rr = lambda kk: (1 - kk) / (1 + kk)
check("E  velocity addition r_{s+t} = (r_s + r_t)/(1 + r_s r_t)  (k_{s+t} = k_s k_t)",
      sp.cancel(rr(ks * kt) - (rr(ks) + rr(kt)) / (1 + rr(ks) * rr(kt))) == 0)
check("E  matrix product [[1,r_s],[r_s,1]][[1,r_t],[r_t,1]] has r-parameter (r_s+r_t)/(1+r_s r_t)",
      (lambda M: sp.cancel(M[0, 1] / M[0, 0] - (rr(ks) + rr(kt)) / (1 + rr(ks) * rr(kt))) == 0 and sp.cancel(M[0, 0] - M[1, 1]) == 0 and sp.cancel(M[0, 1] - M[1, 0]) == 0)(
          sp.Matrix([[1, rr(ks)], [rr(ks), 1]]) * sp.Matrix([[1, rr(kt)], [rr(kt), 1]])))
check("E  (1+r)/(1-r) = 1/k  =>  2 artanh(r) = ln((1+r)/(1-r)) = -ln k = 2 pi t", sp.simplify((1 + r) / (1 - r) - 1 / k) == 0)
Pr = (1 - r**2) / (1 - 2 * r * cosR + r**2)
identity("E  Poisson: push-forward density 1/R'(x) = E/(2k) equals (1-r^2)/(1-2r cos(2 pi R)+r^2)", E / (2 * k) - Pr)

# ==============================================================================================
# Section 4 and Appendices D, F  (resolution time, unresolved fraction)
# ==============================================================================================
a, b = sp.symbols("a b", positive=True)
check("4  tan(pi/2 - a) = cot(a)  (x = n + 1/2 - eps  =>  T = cot(pi eps))", sp.simplify(sp.tan(sp.pi / 2 - a) - 1 / sp.tan(a)) == 0)
check("4  solving k cot(a) = tan(b) for k gives k = tan(a) tan(b)   (a = pi eps, b = pi delta)",
      [sp.simplify(sol - sp.tan(a) * sp.tan(b)) for sol in sp.solve(sp.Eq(k / sp.tan(a), sp.tan(b)), k)] == [0])
check("4  1 - tan a tan b = cos(a+b)/(cos a cos b)  => t*>0 iff eps+delta<1/2 (a,b in (0,pi/2))",
      sp.simplify(1 - sp.tan(a) * sp.tan(b) - sp.cos(a + b) / (sp.cos(a) * sp.cos(b))) == 0)
zz = sp.symbols("zz", positive=True)
check("F  d/dz (tan z - z) = tan^2 z > 0, value 0 at 0  =>  tan z > z on (0, pi/2)  =>  estimate overshoots",
      sp.simplify(sp.diff(sp.tan(zz) - zz, zz) - sp.tan(zz) ** 2) == 0)
ser = sp.series(sp.log(sp.tan(zz) / zz), zz, 0, 6).removeO()
check("F  ln(tan z/z) = z^2/3 + 7 z^4/90 + ...", sp.expand(ser - (zz**2 / 3 + 7 * zz**4 / 90)) == 0)
ee = sp.symbols("ee", positive=True)
lead = sp.series(sp.log(sp.tan(sp.pi * ee) / (sp.pi * ee)) / (2 * sp.pi), ee, 0, 4).removeO()
check("F  t_approx - t* = (1/2pi)[ln(tan(pi e)/(pi e)) + ln(tan(pi d)/(pi d))] = (pi/6)(e^2 + d^2) + O(e^4+d^4)",
      sp.simplify(lead - sp.pi * ee**2 / 6) == 0)
aa = sp.symbols("aa", positive=True)
check("D  d/da [atan a + atan(1/a)] = 0 and value pi/2 at a=1  =>  atan a + atan(1/a) = pi/2",
      sp.simplify(sp.diff(sp.atan(aa) + sp.atan(1 / aa), aa)) == 0 and sp.simplify((sp.atan(1) + sp.atan(1)) - sp.pi / 2) == 0)
check("D  unresolved = 1 - (2/pi) atan(tan(pi d)/k) = (2/pi) atan(k/tan(pi d))  (via atan a + atan 1/a = pi/2)",
      sp.simplify(1 - (2 / sp.pi) * (sp.pi / 2 - sp.atan(k / sp.tan(b))) - (2 / sp.pi) * sp.atan(k / sp.tan(b))) == 0)

# ==============================================================================================
# Negative controls: WRONG formulas must be rejected, otherwise the checker proves nothing.
# ==============================================================================================
neg = [
    ("dR/dx = 2k/D", dRdx - 2 * k / D),
    ("sin(2 pi R) = 2k s/D", sinR - 2 * k * s / D),
    ("dR/dt = +sin(2 pi R)", dRdt - sinR),
    ("D^2 + (1-k)^2 s^2 = 2D", D**2 + ((1 - k) * s) ** 2 - 2 * D),
    ("Poisson with r = tanh(2 pi t)", E / (2 * k) - (1 - ((1 - k**2) / (1 + k**2)) ** 2) / (1 - 2 * ((1 - k**2) / (1 + k**2)) * cosR + ((1 - k**2) / (1 + k**2)) ** 2)),
    ("tan(pi R) = k^2 tan(pi x)", sinR * (1 + c) - k**2 * s * (1 + cosR)),
]
CONTROLS = []
for name, expr in neg:
    CONTROLS.append((f"wrong formula: {name}", (not zero_on_circle(expr)) and (not zero_param(expr))))

# ==============================================================================================
# Numbers quoted in Appendix F (50 digits)
# ==============================================================================================
mp.dps = 50
TPm = 2 * mpi
exact = lambda e, d: mlog(1 / (mtan(mpi * d) * mtan(mpi * e))) / TPm
approx = lambda e, d: mlog(1 / (mpi**2 * e * d)) / TPm
table = [  # eps, delta, exact, estimate, estimate-exact  (as printed in Appendix F)
    ("1e-3", "1e-3", "1.834427", "1.834428", 1.0e-6),
    ("1e-6", "1e-4", "3.300299", "3.300299", 5.2e-9),
    ("1e-9", "1e-6", "5.132638", "5.132638", 5.2e-13),
    ("1e-2", "1e-1", "0.729612", "0.735025", 5.4e-3),
    ("0.2", "0.2", "0.101687", "0.147921", 4.6e-2),
]
ok_tab = True
for e_s, d_s, ex_s, ap_s, df in table:
    e, d = mpf(e_s), mpf(d_s)
    ex, ap = exact(e, d), approx(e, d)
    ok_tab &= (f"{float(ex):.6f}" == ex_s) and (f"{float(ap):.6f}" == ap_s)
    ok_tab &= abs(float(ap - ex) / df - 1) < 0.05            # Appendix F quotes 2 significant figures
check("F  all five table rows of Appendix F (exact, estimate, estimate-exact) reproduce at 50 digits", ok_tab)

# ----------------------------------------------------------------------------------------------
# ----------------------------------------------------------------------------------------------
# Finding: the asymptotic of Appendix D needs k << delta << 1, not just both small.
# ----------------------------------------------------------------------------------------------
def unresolved(kv, dv):
    return 1 - (2 / mpi) * matan(mtan(mpi * dv) / kv)


claim = lambda kv, dv: 2 * kv / (mpi**2 * dv)
FIND = []
for kv, dv in ((mpf("1e-8"), mpf("1e-2")), (mpf("1e-4"), mpf("1e-2")), (mpf("1e-3"), mpf("1e-6")), (mpf("1e-5"), mpf("1e-6"))):
    FIND.append((kv, dv, unresolved(kv, dv), claim(kv, dv)))

w_ = max(len(l) for l, _ in ROWS + CONTROLS)
print(f"{'statement':<{w_}}  status\n" + "-" * (w_ + 10))
for l, ok in ROWS:
    print(f"{l:<{w_}}  {'PROVED' if ok else 'FAILED'}")
print("-" * (w_ + 10))
print("Negative controls (a checker that accepts everything proves nothing):")
for l, ok in CONTROLS:
    print(f"  {l:<{w_ - 2}}  {'rejected (good)' if ok else 'ACCEPTED (BAD)'}")
print("-" * (w_ + 10))
print("Finding -- Appendix D states  unresolved ~ 2k/(pi^2 delta)  only for  k << delta << 1.")
print("It actually needs k/tan(pi delta) << 1  (k << delta);  both being small is not enough:")
print(f"  {'k':>8} {'delta':>8} {'true unresolved':>18} {'2k/(pi^2 delta)':>18}")
for kv, dv, tu, cl in FIND:
    print(f"  {nstr(kv, 3):>8} {nstr(dv, 3):>8} {nstr(tu, 8):>18} {nstr(cl, 8):>18}")
print("-" * (w_ + 10))
allok = all(ok for _, ok in ROWS) and all(ok for _, ok in CONTROLS)
print(f"{sum(ok for _, ok in ROWS)}/{len(ROWS)} statements proved, {sum(ok for _, ok in CONTROLS)}/{len(CONTROLS)} wrong formulas rejected.  "
      + ("ALL EXACT CHECKS PASSED" if allok else "SOME CHECKS FAILED"))
sys.exit(0 if allok else 1)
